---
author: Arthur Katossky & Rémi Pépin
output:
  xaringan::moon_reader:
    css: ["default", "css/presentation.css"]
    nature:
      ratio: 16:10
      scroll: false
---

# 1. Refresher

vocabulary: cluster, node, etc.

## Storage improvement and limits

## Parallelisation

## File systems

## Data base

## Cloud computing

# 2. The fundamental problems of distribution

In this part we do not distinguish between file systems and databases.

# 3. Distributing file systems

## Specific problems of distributed file systems

## An exemple of distributed file system: HDFS

### Why HDFS?

### The architecture

### Role of the master (nodename)

### Role of the slaves

### Properties

How this specific architecture acheives fault-tolerance, etc.

## Other job-schedulers

# 4. Distributing databases

## Specific problems of distributed databases

## An exemple of distributed database: ???????????


# 5. Distributing tasks

## Specific problems of distributed task management

vocabulary: job, task...

## An exemple of job-scheduler: YARN

### The architecture

### Role of the master (job scheduler)

### Role of the slaves

### Properties

How this specific architecture acheives fault-tolerance, etc.

## Other job-schedulers

# 5. Parallezing compution on distributed data

## Map-reduce principle

## Map-shuffle-reduce principle

## An exemple of parallelized compuration framework: Spark

## Other frameworks

# 6. Conclusions and perspectives

## What to remember from today?

## What to remember from the course?

Is big data a problem for you?
Is it worth it?

Key insights:
- use sampling
- maybe you can afford waiting
- beware of the cost
- low level is faster
- think befor you do

## Now you understand this:

--> quotes explaining what this or this software is


<!-- fast languages must be moved to the first course:
Fast languages (Go, Julia, JavaScript) -->